SET PATH=C:\Keil_v5\ARM\ARMCC\Bin;C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeMX\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\MATLAB\R2016b\runtime\win64;C:\Program Files\MATLAB\R2016b\bin;C:\Program Files\MATLAB\R2016b\polyspace\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Users\KONGZELUN\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\KONGZELUN\AppData\Local\Programs\Python\Python36\;C:\Users\KONGZELUN\AppData\Local\Microsoft\WindowsApps;C:\gcc-arm-none-eabi\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files\Java\jre1.8.0_121\bin
SET CPU_TYPE=STM32L476RGTx
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=NUCLEO-L476RG
SET CPU_CLOCK=0x04C4B400
"C:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "nucleo-l476rg\stm32l4xx_hal_tim.__i"
"C:\Keil_v5\ARM\ARMCC\Bin\ArmLink" --Via "NUCLEO-L476RG\NUCLEO-L476RG.lnp"
